//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kevin_Bhavin_Gametracker {
    
    
    public partial class Logout {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Kevin_Bhavin_Gametracker.Site Master {
            get {
                return ((Kevin_Bhavin_Gametracker.Site)(base.Master));
            }
        }
    }
}
